### ISSUE TITLE
Indonesian Language for ionic present

### ISSUE THREAD

**Issue by RizRiyz** [ionic-team/ionic-present#1]
Hi Ionic Team,

I've created the ionic present in Indonesian Language and was presented at Seminar make your own Android in Indonesia, please let me know if I can grant acces to send pull request for branch "id" for this repository :D . 

Anywa here is the link for id language https://github.com/ariestiyansyah/ionic-seminar

**Comment by perrygovier** [comment]
Awesome, thanks. We really need to add better i8n support. I'm curious, what would be the best way to have language specific slides that use the same code examples?

**Comment by grillorafael** [comment]
I think the easiest thing to do is to keep a language folder with the body content. (I think it is easy to do and to receive contributions) and check with a query string. ?lang=en (default) will fetch en content, ?lang=pt-br will fetch pt-br content. What do you think? (No complex i18n solution)

**Comment by aloisdg** [comment]
I started a french version [here](https://github.com/aloisdg/ionic-present).
